insert into form_type (id, form_desc) values('01', 'ก.01');
insert into form_type (id, form_desc) values('04', 'ก.04');
insert into form_type (id, form_desc) values('05', 'ก.05');
insert into form_type (id, form_desc) values('06', 'ก.06');
insert into form_type (id, form_desc) values('07', 'ก.07');
insert into form_type (id, form_desc) values('08', 'ก.08');

insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'descriptiontest', 'ก.01', 'ต้นฉบับ', 'false', '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description', 'ก.01', 'ต้นฉบับ', 'true', '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description2', 'ก.01', 'สำเนา', 'false', '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description3', 'ก.04', 'ทั้งหมด', 'false', '04');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description4', 'ก.08', 'สำเนา', 'false', '08');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description5', 'ก.07', 'ต้นฉบับ', 'false', '07');
insert into document (id, description, category, type, parent_id, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description6', 'ก.01', 'ต้นฉบับ', 2, 'false', '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description7', 'ก.05', 'ต้นฉบับ', 'false', '05');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description8', 'ก.06', 'ต้นฉบับ', 'false', '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description9', 'ก.06', 'สำเนา', 'false', '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description10', 'ก.05', 'ต้นฉบับ', 'false', '05');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description11', 'ก.06', 'ทั้งหมด', 'false', '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, 'description12', 'ก.06', 'ต้นฉบับ', 'false', '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.01', 'ต้นฉบับ', 'false', 1, '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.01', 'สำเนา', 'false', 3, '01');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.04', 'ทั้งหมด', 'false', 4, '04');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.08', 'สำเนา', 'false', 5, '08');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.07', 'ต้นฉบับ', 'false', 6, '07');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.05', 'ต้นฉบับ', 'false', 8, '05');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.06', 'ต้นฉบับ', 'false', 9, '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.06', 'สำเนา', 'false', 10, '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.05', 'ต้นฉบับ', 'false', 11, '05');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.06', 'ทั้งหมด', 'false', 12, '06');
insert into document (id, description, category, type, FLAG_HAS_SUB, parent_id, FORM_TYPE_ID) values(DOCUMENT_SEQ.nextVal, '', 'ก.06', 'ต้นฉบับ', 'false', 13, '06');